### ISSUE TITLE
warning_accumulator can give a TypeError

### ISSUE THREAD

**Issue by mivade** [pennmem/ram_utils#90]
```pytb
Traceback (most recent call last):
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/bin/ramulator-conf", line 11, in <module>
    load_entry_point('ramutils==2.0.2', 'console_scripts', 'ramulator-conf')()
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/ramutils-2.0.2-py3.6.egg/ramutils/cli/expconf.py", line 172, in main
    warnings = '\n' + warning_accumulator.format_all()
TypeError: must be str, not NoneType
```

**Comment by zduey** [comment]
Fixed as part of commit 0696d07
